### PR TITLE
Feature: psd producer stability and text masks

### PR DESCRIPTION
**Pull request by Julusian**
Sponsored by @didikunz and Media Support

This is some improvements for the PSD and scene producers, to fix some major bugs, make it possible to do some text masking in PSDs and allow using other cg templates inside of PSDs in a similar way to how videos can be used.

## Key changes
* PSD Text vector masks (CasparCG#1159)
* Fix PSD video playback speed in interlaced (CasparCG#625)
* Load other cg templates (flash, html etc) from PSDs
* Dynamic images and colours in scene producer (CasparCG#670)
* Add scenes/PSDs to DIAG and output some basic OSC data (CasparCG#670)
* Add system time as a scene variable with formatting options (CasparCG#670)
* Fix text rendering with large font size and unicode characters (CasparCG#670)

### Load other templates
The basic syntax is `[cg](AwayLogo>HomeLogo)HomeLogo`
This is broken down as
`[cg]` = the prefix
`(AwayLogo>HomeLogo)` = field mapping
`HomeLogo` = filename

Due to how the PSD producer works, we need to individually specify the fields to pass through. 
The mappings are structured as a list `(AwayLogo>f0,HomeLogo>f1)` and if the same name is used on both sides, then it can be used just once. eg `(HomeLogo>HomeLogo)` is the same as `(HomeLogo)`
Doing a call with new data on the psd producer will propagate the data through.

play() and stop() of the template are controlled by the first and last frame of the layer on the timeline. This means the out animation will start when the layer ends in the PSD.

### CODE REVIEW

**Comment by didikunz** [comment]
Is there a build somewhere, that supports this feature? On builds.casparcg.com the last 2.1.x is from September 2017 and the last for Windows from April 2017. Then I tried a few 2.2.x versions and the last build in "master" from December 2019: They don't even list templates with the .psd extension. There are also no 2.1.8 NRK build around, are they?

**Comment by Julusian** [comment]
Not yet. It will be in 2.1.11, but that hasn't been done yet.
In general builds are on the releases https://github.com/nrkno/tv-automation-casparcg-server/releases, and there arent any published dev builds for the nrk fork.
Yes, 2.2 will not list psd templates as psd support was removed there and nothing has been done on trying to get it back into 2.3.

**Comment by didikunz** [comment]
Thanks, when do you expect the 2.1.11 build to be released?

**Comment by Julusian** [comment]
@didikunz I have just published 2.1.11 https://github.com/nrkno/tv-automation-casparcg-server/releases/tag/v2.1.11_NRK

**Comment by didikunz** [comment]
@Julusian: Thank you very much! Locks very promising.

**Comment by DavidORiley** [comment]
This looks great, could I use it to load an image within a PSD layer? Is there anyway of hiding individual layers of a PSD through CG commands?

**Pull request merged**
