### PR TITLE
Linux fixes

### PR DESCRIPTION
**Pull request by dimitry-ishenko**
@Julusian this is work-in-progress. Let me know what you think so far. I am fighting with Boost at the moment and should have the rest soon...

### CODE REVIEW

**Comment by dimitry-ishenko** [comment]
@Julusian I need some help with this...

This PR makes it so that everything compiles fine, but I get this error during linking:
```bash
[ 98%] Linking CXX executable casparcg
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libboost_locale.a(boundary.o): undefined reference to symbol 'ucnv_getMaxCharSize_66'
/usr/bin/ld: /lib/x86_64-linux-gnu/libicuuc.so.66: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [shell/CMakeFiles/casparcg.dir/build.make:171: shell/casparcg] Error 1
make[1]: *** [CMakeFiles/Makefile2:791: shell/CMakeFiles/casparcg.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

So, I've added references to the ICU (intensive care unit :rofl:) libraries, which is included in the last commit, but that causes Boost to explode sky high. Here is just a tip of the iceberg:
```bash
[ 98%] Linking CXX executable casparcg
/usr/bin/ld: CMakeFiles/casparcg.dir/main.cpp.o: in function `boost::locale::generator::operator()(std::string const&) const':
/usr/include/boost/locale/generator.hpp:203: undefined reference to `boost::locale::generator::generate(std::string const&) const'
/usr/bin/ld: CMakeFiles/casparcg.dir/main.cpp.o: in function `boost::enable_if_c<(boost::log::v2s_mt_posix::aux::is_character_type<char>::value&&boost::log::v2s_mt_posix::aux::is_character_type<wchar_t>::value)&&((sizeof (char))!=(sizeof (wchar_t))), bool>::type boost::log::v2s_mt_posix::aux::code_convert<char, wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >(char const*, unsigned long, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, unsigned long, std::locale const&)':
/usr/include/boost/log/detail/code_conversion.hpp:133: undefined reference to `boost::log::v2s_mt_posix::aux::code_convert_impl(char const*, unsigned long, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, unsigned long, std::locale const&)'
/usr/bin/ld: /usr/include/boost/log/detail/code_conversion.hpp:133: undefined reference to `boost::log::v2s_mt_posix::aux::code_convert_impl(char const*, unsigned long, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, unsigned long, std::locale const&)'
/usr/bin/ld: /usr/include/boost/log/detail/code_conversion.hpp:133: undefined reference to `boost::log::v2s_mt_posix::aux::code_convert_impl(char const*, unsigned long, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, unsigned long, std::locale const&)'
/usr/bin/ld: CMakeFiles/casparcg.dir/server.cpp.o: in function `boost::enable_if_c<(boost::log::v2s_mt_posix::aux::is_character_type<char>::value&&boost::log::v2s_mt_posix::aux::is_character_type<wchar_t>::value)&&((sizeof (char))!=(sizeof (wchar_t))), bool>::type boost::log::v2s_mt_posix::aux::code_convert<char, wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >(char const*, unsigned long, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, unsigned long, std::locale const&)':
/usr/include/boost/log/detail/code_conversion.hpp:133: undefined reference to `boost::log::v2s_mt_posix::aux::code_convert_impl(char const*, unsigned long, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, unsigned long, std::locale const&)'
/usr/bin/ld: CMakeFiles/casparcg.dir/server.cpp.o: in function `boost::filesystem::path_traits::convert(char const*, char const*, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&)':
/usr/include/boost/filesystem/path.hpp:1002: undefined reference to `boost::filesystem::path_traits::convert(char const*, char const*, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, std::codecvt<wchar_t, char, __mbstate_t> const&)'
/usr/bin/ld: /usr/include/boost/filesystem/path.hpp:1002: undefined reference to `boost::filesystem::path_traits::convert(char const*, char const*, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, std::codecvt<wchar_t, char, __mbstate_t> const&)'
/usr/bin/ld: CMakeFiles/casparcg.dir/server.cpp.o: in function `boost::filesystem::path_traits::convert(wchar_t const*, wchar_t const*, std::string&)':
/usr/include/boost/filesystem/path.hpp:1010: undefined reference to `boost::filesystem::path_traits::convert(wchar_t const*, wchar_t const*, std::string&, std::codecvt<wchar_t, char, __mbstate_t> const&)'
...
```

I am kind of stumped. Tried various suggestions from the interwebs, but nothing seems to help.

Please take a look if you could.

**Comment by dimitry-ishenko** [comment]
@Julusian I need some help with this...

This PR makes it so that everything compiles fine, but I get this error during linking:
```bash
[ 98%] Linking CXX executable casparcg
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libboost_locale.a(boundary.o): undefined reference to symbol 'ucnv_getMaxCharSize_66'
/usr/bin/ld: /lib/x86_64-linux-gnu/libicuuc.so.66: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [shell/CMakeFiles/casparcg.dir/build.make:171: shell/casparcg] Error 1
make[1]: *** [CMakeFiles/Makefile2:791: shell/CMakeFiles/casparcg.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

I've tried linking against ICU (intensive care unit :rofl:) libraries, but that causes Boost to explode sky high. Here is just a tip of the iceberg:
```bash
[ 98%] Linking CXX executable casparcg
/usr/bin/ld: CMakeFiles/casparcg.dir/main.cpp.o: in function `boost::locale::generator::operator()(std::string const&) const':
/usr/include/boost/locale/generator.hpp:203: undefined reference to `boost::locale::generator::generate(std::string const&) const'
/usr/bin/ld: CMakeFiles/casparcg.dir/main.cpp.o: in function `boost::enable_if_c<(boost::log::v2s_mt_posix::aux::is_character_type<char>::value&&boost::log::v2s_mt_posix::aux::is_character_type<wchar_t>::value)&&((sizeof (char))!=(sizeof (wchar_t))), bool>::type boost::log::v2s_mt_posix::aux::code_convert<char, wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >(char const*, unsigned long, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, unsigned long, std::locale const&)':
/usr/include/boost/log/detail/code_conversion.hpp:133: undefined reference to `boost::log::v2s_mt_posix::aux::code_convert_impl(char const*, unsigned long, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, unsigned long, std::locale const&)'
/usr/bin/ld: /usr/include/boost/log/detail/code_conversion.hpp:133: undefined reference to `boost::log::v2s_mt_posix::aux::code_convert_impl(char const*, unsigned long, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, unsigned long, std::locale const&)'
/usr/bin/ld: /usr/include/boost/log/detail/code_conversion.hpp:133: undefined reference to `boost::log::v2s_mt_posix::aux::code_convert_impl(char const*, unsigned long, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, unsigned long, std::locale const&)'
/usr/bin/ld: CMakeFiles/casparcg.dir/server.cpp.o: in function `boost::enable_if_c<(boost::log::v2s_mt_posix::aux::is_character_type<char>::value&&boost::log::v2s_mt_posix::aux::is_character_type<wchar_t>::value)&&((sizeof (char))!=(sizeof (wchar_t))), bool>::type boost::log::v2s_mt_posix::aux::code_convert<char, wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >(char const*, unsigned long, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, unsigned long, std::locale const&)':
/usr/include/boost/log/detail/code_conversion.hpp:133: undefined reference to `boost::log::v2s_mt_posix::aux::code_convert_impl(char const*, unsigned long, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, unsigned long, std::locale const&)'
/usr/bin/ld: CMakeFiles/casparcg.dir/server.cpp.o: in function `boost::filesystem::path_traits::convert(char const*, char const*, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&)':
/usr/include/boost/filesystem/path.hpp:1002: undefined reference to `boost::filesystem::path_traits::convert(char const*, char const*, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, std::codecvt<wchar_t, char, __mbstate_t> const&)'
/usr/bin/ld: /usr/include/boost/filesystem/path.hpp:1002: undefined reference to `boost::filesystem::path_traits::convert(char const*, char const*, std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, std::codecvt<wchar_t, char, __mbstate_t> const&)'
/usr/bin/ld: CMakeFiles/casparcg.dir/server.cpp.o: in function `boost::filesystem::path_traits::convert(wchar_t const*, wchar_t const*, std::string&)':
/usr/include/boost/filesystem/path.hpp:1010: undefined reference to `boost::filesystem::path_traits::convert(wchar_t const*, wchar_t const*, std::string&, std::codecvt<wchar_t, char, __mbstate_t> const&)'
...
```

I am kind of stumped. Tried various suggestions from the interwebs, but nothing seems to help.

Please take a look if you could.

**Comment by dimitry-ishenko** [comment]
@Julusian I found the problem:
```cmake
add_definitions( -D_GLIBCXX_USE_CXX11_ABI=0 ) # Allow compilation in GCC 5 while keeping old dependencies
```
The boost libraries were (obviously) built with C++11 ABI and that's why the linker couldn't find needed symbols.

@Julusian do you care if I bump minimum CMake version to 3.1? Want to use a few newer macros.

**Comment by Julusian** [comment]
That definition line was added for I think boost to resolve some issues, so feel free to try removing it.

Higher cmake requirements are fine with me. Feel free to go a lot higher if you want

**Pull request closed without merging**
